package global;

public enum Activates 
{
	ON_LEVELING, ONCE, NEVER, ON_ATTACK, ON_DAMAGE_TAKEN, ON_SPELL_TRIGGER, 
	COMMAND, EQUIPPED, REMOVED, PICKED_UP, PER_WEEK, PER_DAY, PER_MONTH, PER_YEAR,
	ON_DEATH, ON_TARGET, ON_DYING, ON_PARALYSIS, ON_POISON, ON_ATTACKED, ON_SPOKEN_TO;

}
