package global;

public enum Language 
{
	COMMON, ELVEN, SYLVAN, ORC, GOBLIN, GIANT, 
	UNDERCOMMON, DRACONIC, CELESTIAL, INFERNAL, 
	AURAN, TERRAN, AQUAN, IGNAN, DRUIDIC, GREP,
	ABOLETH, ABYSSAL, AKLO, BOGGARD, CYCLOPS,
	DARK_FOLK, DROW_SIGN, DWARVEN,  DZIRIAK,
	GNOLL, GNOME, GRIPPLI, HALFLING, NECRIL,
	PROTEAN, SPHINX, TENGU, TREANT, VEGEPYGMY;

}
